# Generated by Django 5.2.10 on 2026-04-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
