# Generated by Django 5.2.10 on 2026-04-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_products_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='Category',
        ),
    ]
