# Generated by Django 5.2.10 on 2026-04-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='categories',
        ),
    ]
